Add user details in password login response
KeyValueSoftwareSystems/authentication-service pull request #41
Opened 2022-10-18 11:35 UTC by alphinroy-kv

2022-10-18 11:41 UTC, doylefermi-kv requested changes
Lets's make use of the existing type `User`

2022-10-19 07:01 UTC, JoyalAJohney-KeyValue commented
LGTM, @doylefermi-kv any further changes?

2022-10-19 08:31 UTC, doylefermi-kv approved these changes

2022-10-19 08:31 UTC, doylefermi-kv commented on src/authentication/authentication.graphql
> +  user: User
Can we ensure that user is mandatory in the schema?

2022-10-19 11:51 UTC, doylefermi-kv requested changes

2022-10-19 11:51 UTC, doylefermi-kv commented on src/authentication/service/token.service.ts
> +    return { ...token, user: userRecord };
Can we create a new variable of type TokenResponse and return it? Let's not skip 1 line of code compromising readability.

2022-10-19 11:51 UTC, doylefermi-kv commented on test/authentication/resolver/userauth.resolver.test.ts
> +          id: 'ae032b1b-cc3c-4e44-9197-276ca877a7f8',
Let's not reintroduce a new string. Let's reuse the existing `users[]`. The only difference is, this local variable will not have the password and other unwanted details.

Example: [Code reference](https://github.com/KeyValueSoftwareSystems/authentication-service/blob/ea9b3ec6593f92ae1b545c75aed6f32ebbc5dfed/test/authentication/resolver/userauth.resolver.test.ts#L124-L130)

2022-10-19 13:16 UTC, doylefermi-kv commented on src/authentication/service/token.service.ts
> +    const token = this.authenticationHelper.generateTokenForUser(userRecord);
Please ignore this line since there is no code change.

2022-10-19 13:16 UTC, doylefermi-kv approved these changes

2022-10-20 05:50 UTC, merged