Add user status
KeyValueSoftwareSystems/authentication-service pull request #46
Opened 2022-10-26 11:15 UTC by swathikrishna-kv

2022-10-27 04:49 UTC, doylefermi-kv requested changes

2022-10-27 04:49 UTC, doylefermi-kv commented on src/schema/graphql.schema.ts
> +    status: string;
Can we make use of [Graphql Enum](https://graphql.org/learn/schema/#enumeration-types) to ensure this is a well defined value and not some random string?

2022-10-27 04:49 UTC, doylefermi-kv commented on src/authorization/entity/user.entity.ts
> +  public status!: string;
Can we make use of the [Typeorm Enum](https://github.com/typeorm/typeorm/blob/master/docs/entities.md#enum-column-type) datatype here?

2022-10-27 04:49 UTC, doylefermi-kv commented on src/authorization/entity/user.entity.ts
> +  public inviteToken?: string;
Is this part of this PR? Or a separate feature?

2022-10-27 04:49 UTC, doylefermi-kv commented on src/migrations/1666763401586-User Status Invite Token.ts
> +      `ALTER TABLE "user" ADD "invite_token" character varying`,
Is this part of this PR or a different feature?

2022-10-27 04:49 UTC, doylefermi-kv commented on src/migrations/1666763401586-User Status Invite Token.ts
> +      `ALTER TABLE "entity_permission" DROP CONSTRAINT "PK_ac18341de235a9dddb822c35892"`,
Why are we dropping this constraint?

2022-10-27 04:49 UTC, doylefermi-kv commented on src/migrations/1666763401586-User Status Invite Token.ts
> +      `ALTER TABLE "entity_permission" DROP COLUMN "permission_id"`,
Please review this change.

2022-10-27 04:49 UTC, doylefermi-kv commented on src/authorization/service/user.service.ts
> +    if (user.status == 'inactive') {
Can we reuse the Enum datatype here for status?

2022-10-27 04:49 UTC, doylefermi-kv commented on src/authorization/service/user.service.ts
> +      throw new AccountIsInactive();
Can we rename this to `InactiveAccountException()`?

2022-10-27 04:49 UTC, doylefermi-kv commented on src/authorization/service/user.service.ts
> +    await this.updateField(id, 'status', 'inactive');
What if softDelete fails? Shouldn't we make this operation atomic?

2022-10-27 04:49 UTC, doylefermi-kv commented on src/authorization/exception/user.exception.ts
> +    super(`Account is inactive`);
What would be the status code thrown for this exception? `BadRequestException` throws `400` which indicates that the request is incorrect. Can we put in a more appropriate status code here?

2022-10-27 04:49 UTC, doylefermi-kv commented on src/authorization/graphql/user.graphql
> +  status: String!
Can we make use of [Graphql Enum](https://graphql.org/learn/schema/#enumeration-types) to ensure this is a well defined value and not some random string?

2022-10-27 04:49 UTC, doylefermi-kv commented on src/authorization/exception/user.exception.ts
> +import { BadRequestException } from '@nestjs/common';
Should this exception be thrown globally whenever an inactive user tries to perform operations?

2022-10-28 05:04 UTC, doylefermi-kv requested changes

2022-10-28 08:28 UTC, doylefermi-kv approved these changes

2022-10-28 08:28 UTC, doylefermi-kv commented on src/authorization/service/user.service.ts
> +  InactiveAccountException,
Can we remove this unused import?

2022-10-28 08:28 UTC, doylefermi-kv commented on src/authorization/exception/user.exception.ts
> +import { ForbiddenException } from '@nestjs/common';
Please remove this unused import

2022-10-28 08:28 UTC, doylefermi-kv commented on src/authorization/exception/user.exception.ts
> +import { ForbiddenException } from '@nestjs/common';
Can we remove this unused import?

2022-10-28 10:55 UTC, JoyalAJohney-KeyValue approved these changes

2022-10-28 11:24 UTC, merged