Generic search
KeyValueSoftwareSystems/authentication-service pull request #47
Opened 2022-10-27 11:47 UTC by JoyalAJohney-KeyValue

2022-10-28 10:11 UTC, doylefermi-kv requested changes

2022-10-28 10:11 UTC, doylefermi-kv commented on src/authorization/graphql/user.graphql
> +input SearchCondition {
Can we make this `StringSearchCondition`? This would vary for other types like `IntSearchCondition` or `FloatSearchCondition`

2022-10-28 10:11 UTC, doylefermi-kv commented on src/authorization/service/user.service.ts
> +  public generateWhereClauseForSearchTerm(
Can we move this to a utility function since this is going to be generic?

2022-10-28 10:27 UTC, doylefermi-kv requested changes

2022-10-28 10:27 UTC, doylefermi-kv commented on src/authorization/service/user.service.ts
> +  public generateWhereClauseForSearchTerm(
`generateWhereClauseForStringSearch`

2022-10-31 06:12 UTC, JoyalAJohney-KeyValue commented on src/authorization/graphql/user.graphql
> +input UserSearchCondition {
UserSearchParameter

2022-10-31 06:12 UTC, JoyalAJohney-KeyValue commented on src/authorization/graphql/user.graphql
> +input UserSearchInput {
UserSearchCondition

2022-11-02 05:34 UTC, doylefermi-kv requested changes

2022-11-02 05:34 UTC, doylefermi-kv commented on src/authorization/service/group.service.ts
> +  createQueryBuilder,
Lets remove this unused import.

2022-11-02 05:34 UTC, doylefermi-kv commented on src/authorization/service/group.service.ts
> +import UserService from './user.service';
Lets remove this unused import.

2022-11-02 05:34 UTC, doylefermi-kv commented on src/authorization/service/role.service.ts
> +import UserService from './user.service';
Lets remove this unused import.

2022-11-02 05:34 UTC, doylefermi-kv commented on src/authorization/service/role.service.ts
> +    let searchTerm: { [key: string]: FindOperator<string | undefined> }[] = [];
This logic is being rewritten across Users / Groups / Roles ... and any other future entities. Can we move this generic logic to SearchService?

2022-11-02 05:34 UTC, doylefermi-kv commented on src/authorization/service/role.service.ts
> +  generateSearchTermForRole(
This logic is being rewritten across Users / Groups / Roles ... and any other future entities. Can we move this generic logic to SearchService?

Or if not should we just move this function to SearchService?

2022-11-02 05:34 UTC, doylefermi-kv commented on src/authorization/service/user.service.ts
> +  Equal,
Lets remove this unused import.

2022-11-02 05:35 UTC, doylefermi-kv requested changes

2022-11-02 05:35 UTC, doylefermi-kv commented on src/authorization/service/search.service.ts
> +import { Injectable } from '@nestjs/common';
Can we add a test to cover this new service?

2022-11-02 07:07 UTC, doylefermi-kv approved these changes
Please log a tracking issue to cover tests.

2022-11-02 11:00 UTC, merged