Create user api
KeyValueSoftwareSystems/authentication-service pull request #48
Opened 2022-10-31 08:02 UTC by alphinroy-kv

2022-11-02 06:43 UTC, doylefermi-kv requested changes
- Can we write tests to cover the new functionality introduced?
- Please run `npm run lint` to fix all linter warnings and code formatting.

2022-11-02 06:43 UTC, doylefermi-kv commented on src/authentication/authentication.graphql
> +    revokeToken(id: ID!): String
Can we make this `revokeInviteToken`?

2022-11-02 06:43 UTC, doylefermi-kv commented on src/authentication/authentication.helper.ts
> +    return jwt.sign(payload, process.env.JWT_SECRET || '', {
Can we use `configService` to obtain the values for env variables?

2022-11-02 06:43 UTC, doylefermi-kv commented on src/authentication/service/password.auth.service.ts
> +import { PasswordAlreadySetException, UserNotFoundException } from '../../authorization/exception/user.exception';
Can we rerun `npm run lint` and confirm if everything is good?

2022-11-02 06:43 UTC, doylefermi-kv commented on src/authentication/service/password.auth.service.ts
> +    const verifyObj = await this.userService.verifyDuplicateUser(
Please rename this variable `verifyObj`.

2022-11-02 06:43 UTC, doylefermi-kv commented on src/authentication/service/password.auth.service.ts
> +    return { inviteToken: token };
Can we return the expiry time of the token as well?

2022-11-02 06:43 UTC, doylefermi-kv commented on src/authentication/service/password.auth.service.ts
> +  async setPasswordForInvite(
Can we rename this to `setPasswordForInvitedUser` ?

2022-11-02 06:43 UTC, doylefermi-kv commented on src/authentication/service/token.service.ts
> +    return { inviteToken: token };
Can we return the expiry time of the token as well?

2022-11-02 06:43 UTC, doylefermi-kv commented on src/authentication/service/token.service.ts
> +    return 'Success';
Can we return a boolean value instead of a hardcoded string?

2022-11-03 05:06 UTC, doylefermi-kv requested changes

2022-11-03 05:06 UTC, doylefermi-kv commented on src/authentication/service/token.service.ts
> +    return true;
Can we correct the mismatch in schema and the return type?

2022-11-03 05:06 UTC, doylefermi-kv commented on src/authentication/authentication.graphql
> +    revokeInviteToken(id: ID!): String
Let's ensure it returns a mandatory value and not null in graphql. Same with the other mutations as well.

2022-11-03 05:06 UTC, doylefermi-kv commented on src/authentication/service/password.auth.service.ts
> +    );
Should we first create a user and then update the token or should we create a new user with the token making the operation atomic?
- How do we address the scenario when user creation without password was successful but creation and updating invite token failed.

2022-11-03 07:16 UTC, JoyalAJohney-KeyValue commented on src/authentication/resolver/user.auth.resolver.ts
> +  async refreshInviteToken(
Let's keep edit-user permission for this mutation

2022-11-03 07:16 UTC, JoyalAJohney-KeyValue commented on src/authentication/resolver/user.auth.resolver.ts
> +  async revokeInviteToken(
Let's keep edit-user permission for this mutation

2022-11-04 04:08 UTC, doylefermi-kv approved these changes

2022-11-04 05:31 UTC, JoyalAJohney-KeyValue approved these changes

2022-11-04 08:35 UTC, merged